spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/habitflow}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
